/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("fastSwiss.kotlin-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":api"))
    implementation("dev.inmo:tgbotapi:5.0.1")

}

application {
    // Define the main class for the application.
    mainClass.set("fastSwiss.telegramBot.AppKt")
}
